fixing entrypoint to provide jasper specific config under /etc/opt/bitnami/jasperreports/config/
bitnami/bitnami-docker-jasperreports pull request #104
Opened 2021-11-28 03:56 UTC by guaychou

**Description of the change**

I'm trying to fixing this issue https://github.com/bitnami/bitnami-docker-jasperreports/issues/68 with minimal effort as i can, i added some code to entrypoint to read /etc/opt/bitnami/jasperreports/config/ which is should be added by the user when they need to add jasper specific config file like editing jasperserver-servlet.xml etc.

**Benefits**

User now can add their specific config

**Possible drawbacks**

none

**Applicable issues**

https://github.com/bitnami/bitnami-docker-jasperreports/issues/68

**Additional information**

2021-11-29 10:28 UTC, javsalgar commented
Hi,

Thank you so much for the PR! Normally, the path we would use for this would be `/bitnami/jasperreports/mounted-conf`, could you change that? Also, wouldn't there be any side-effects in doing it after the initialization?

2021-11-29 10:41 UTC, guaychou commented
> 

it will doesn't work when we mount under /bitnami/jasperreports folder, because another script will detect that persistent data already there but they are not found (especially in initial phase) that's why we need to use another to not break anything

something like this 
![image](https://user-images.githubusercontent.com/29087469/143853555-96f6910f-94e9-4773-a608-7e1ec391a035.png)

2021-12-03 11:44 UTC, rafariossaa commented
Hi,
  Sorry for the delay, @javsalgar is on PTO, he will return soon. I would like him to give you his thoughts on this change.

2021-12-03 16:07 UTC, splattner commented
When you run this image in a Kubernetes Cluster and mount `/etc/opt/bitnami/jasperreports/config` from a ConfigMap then the entries in the directory are only symlinks. The `cp -r` only copies the symlink and therefore at the target location the symlinks are not valid anymore.
Therefore I suggest using `cp -r -L` to follow the symlink and copy the real file.

2021-12-09 09:17 UTC, javsalgar commented
> it will doesn't work when we mount under /bitnami/jasperreports folder, because another script will detect that persistent data already there but they are not found (especially in initial phase) that's why we need to use another to not break anything


I see, I've checked the libpersistence.sh functions and indeed, that would happen. Could you, at least for consistency, change it to /bitnami/jasperreports-mounted-conf/, so it is in the volume directory.

2021-12-11 05:49 UTC, guaychou commented
> > it will doesn't work when we mount under /bitnami/jasperreports folder, because another script will detect that persistent data already there but they are not found (especially in initial phase) that's why we need to use another to not break anything
> 
> I see, I've checked the libpersistence.sh functions and indeed, that would happen. Could you, at least for consistency, change it to /bitnami/jasperreports-mounted-conf/, so it is in the volume directory.

i have updated the script for this one

2021-12-13 12:51 UTC, rafariossaa commented on docker-compose.yml
> +      - ${PWD}/config:/bitnami/jasperreports-mounted-conf
Hi,
  What do you think about leaving out this change ? I think that it would be better if the provided basic  `docker-compose` does not add any extra thing. This would be commented in the README, so any user can customize it as needed.

2021-12-18 07:18 UTC, guaychou commented on docker-compose.yml
> +      - ${PWD}/config:/bitnami/jasperreports-mounted-conf
okay, will do some change

2021-12-21 07:07 UTC, guaychou commented on docker-compose.yml
> +      - ${PWD}/config:/bitnami/jasperreports-mounted-conf
done @rafariossaa

2021-12-22 08:23 UTC, rafariossaa commented on docker-compose.yml
> +      - ${PWD}/config:/bitnami/jasperreports-mounted-conf
Thanks @guaychou

2022-01-04 15:20 UTC, marcosbc requested changes
Thanks for the contribution! Please have a look at my requests.

2022-01-04 15:20 UTC, marcosbc commented on 7/debian-10/rootfs/opt/bitnami/scripts/jasperreports/entrypoint.sh
> +    fi
This logic is something we add to the `jasperreports_initialize` function. In addition, note that the first `if` is not indented.

FYI, this is how we are doing it in other images like Discourse:

```
if ! is_dir_empty "${DISCOURSE_BASE_DIR}/mounted-conf"; then
    info "Detected mounted configuration files, copying to Discourse config directory"
    cp -r "${DISCOURSE_BASE_DIR}/mounted-conf/"* "$DISCOURSE_CONF_DIR"
fi
```

You can see that we are also using environment variables, and using a specific comment style.

Could you make those changes?

2022-01-04 15:20 UTC, marcosbc commented on README.md
> +#     - ${PWD}/config:/bitnami/jasperreports-mounted-conf
```suggestion
     # The line below allows you to provide your own JasperReports configuration files, to be copied to WEB-INF
     - "./config:/opt/bitnami/jasperreports/mounted-conf"
```

2022-01-04 15:20 UTC, marcosbc commented on docker-compose.yml
> +      - ${PWD}/config:/bitnami/jasperreports-mounted-conf
We should avoid modifying the default `docker-compose.yml`, since this is not something that all users would do.

2022-01-04 16:54 UTC, guaychou commented on 7/debian-10/rootfs/opt/bitnami/scripts/jasperreports/entrypoint.sh
> +    fi
okayy

2022-01-19 06:44 UTC, guaychou commented on docker-compose.yml
> +      - ${PWD}/config:/bitnami/jasperreports-mounted-conf
it should be okay now

2022-01-19 06:45 UTC, guaychou commented on 7/debian-10/rootfs/opt/bitnami/scripts/jasperreports/entrypoint.sh
> +    fi
already update @marcosbc can you help to review ? i don;t really where to put the env variable

2022-01-19 07:46 UTC, rafariossaa requested changes
Maybe I am missing something but I think the path are not the right ones.

2022-01-19 07:46 UTC, rafariossaa commented on 7/debian-10/rootfs/opt/bitnami/scripts/jasperreports/entrypoint.sh
> +        cp -r -L /bitnami/jasperreports-mounted-conf/* /opt/bitnami/jasperreports/WEB-INF/
I think this should be:
```suggestion
        cp -r -L /bitnami/jasperreports/mounted-conf/* /opt/bitnami/jasperreports/WEB-INF/
```

2022-01-19 07:46 UTC, rafariossaa commented on README.md
> +# - "./config:/opt/bitnami/jasperreports/mounted-conf"
```suggestion
# - "./config:/bitnami/jasperreports/mounted-conf"
```

2022-01-21 04:09 UTC, guaychou commented on README.md
> +# - "./config:/opt/bitnami/jasperreports/mounted-conf"
it's should be resolved now @rafariossaa

2022-01-21 08:19 UTC, rafariossaa approved these changes
LGTM.

2022-01-21 08:32 UTC, rafariossaa commented
Hi, 
  We need that the commits are signed, could fix it ?
  https://github.com/bitnami/bitnami-docker-jasperreports/pull/104/checks?check_run_id=4891934246

2022-01-21 08:34 UTC, guaychou commented
> Hi,
> We need that the commits are signed, could fix it ?
> https://github.com/bitnami/bitnami-docker-jasperreports/pull/104/checks?check_run_id=4891934246

ohh okay

2022-01-22 07:04 UTC, guaychou commented
@rafariossaa that's should be fixed now

2022-01-24 08:40 UTC, rafariossaa commented
Hi,
  Thanks, LGTM. 
   I am merging it.

2022-01-24 08:40 UTC, merged