ROOT URL setting
bitnami/bitnami-docker-jasperreports pull request #110
Opened 2022-01-15 19:01 UTC by Dreamerset

**Use case**   

After deployment, bitnami jasperreports container defaults at http://example.com/jasperserver URL. It is a result of either typing the entire url address or being redirected from http://example.com  
However, using jasperreporst API through http://example.com is not possible due to the mentioned redirection made in Tomcat's index.jsp.  

**Change**   

Introduced a new configuration Boolean variable `JASPERREPORTS_ROOT_URL` in jasperreports-env.sh  
By default the variable is set to false with no change in the container behavior.   
Introduced an `If` statement to control jasperreports deployment folder based on `JASPERREPORTS_ROOT_URL` value in libjasperreports.sh
Introduced short description of the option in the README file.

**Benefits**

Enables jasperreport API on plain domain address such as http://example.com/

**Possible drawbacks**

Not known.

**Applicable issues**

#109

2022-01-17 10:53 UTC, javsalgar requested changes
Thank you so much! Change requested

2022-01-17 10:53 UTC, javsalgar commented on 7/debian-10/Dockerfile
> +RUN apt-get update && apt-get upgrade -y && \
Could you please remove this? The `install_packages` operations above should be enough

2022-01-17 11:10 UTC, Dreamerset commented on 7/debian-10/Dockerfile
> +RUN apt-get update && apt-get upgrade -y && \
I removed the line.
You should know that line was not intentional change by me. It got there somehow through the pull request creation / checks / sing offs, not even sure how it appeared at all.

2022-01-17 11:37 UTC, Dreamerset commented
There are two more changes in [https://github.com/bitnami/bitnami-docker-jasperreports/pull/110/commits/ba69249206fbfd60660e8cd7578525cba9744fb8](https://github.com/bitnami/bitnami-docker-jasperreports/pull/110/commits/ba69249206fbfd60660e8cd7578525cba9744fb8) which were not intentional.
Let me know if I have to remove them too.

2022-01-19 11:35 UTC, javsalgar reviewed
Change requested

2022-01-19 11:35 UTC, javsalgar commented on 7/debian-10/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +    if $JASPERREPORTS_ROOT_URL; then
Could you use the `! is_empty_value "$JASPERREPPORTS_ROOT_URL"` function?

2022-01-19 17:06 UTC, Dreamerset commented on 7/debian-10/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +    if $JASPERREPORTS_ROOT_URL; then
I could use it, however the current condition is more restrictive. It requires the variable to have a specific value in addition to have a value at all. If the value is anything else (including `null`) than "true" the function will not be executed.  
If we only check for value, it could be anything, as we don't have strong typing on the variable and the test will pass.

Would you like to make the condition combined `! is_empty_value "$JASPERREPPORTS_ROOT_URL" && "$JASPERREPPORTS_ROOT_URL"` which should translate to "$JASPERREPPORTS_ROOT_URL" has value AND it is "true"?  

What is the motivation behind this change request?

2022-01-21 10:27 UTC, javsalgar commented on 7/debian-10/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +    if $JASPERREPORTS_ROOT_URL; then
Oh, I didn't see it was a boolean. Maybe the name should be changed to `JASPERREPORTS_USE_ROOT_URL`. Anyways, in that case we have the function `is_boolean_yes` that you could use

```
if is_boolean_yes "$JASPERREPORTS_ROOT_URL"
```

the reason behind this is for standardization and consistency in the code we use in our containers.

2022-01-21 10:57 UTC, Dreamerset commented on 7/debian-10/rootfs/opt/bitnami/scripts/libjasperreports.sh
> +    if $JASPERREPORTS_ROOT_URL; then
Applied all recommendations.

2022-01-24 14:58 UTC, javsalgar approved these changes
LGTM. Thanks!

2022-01-24 15:06 UTC, javsalgar commented
Could you fix the merge issues?

2022-01-24 16:18 UTC, Dreamerset commented
Merged issues are fixed, however if the change is not merged soon, tomorrow new ones will appear due to the debian version change as part of the docker image. Which seems to be updated automatically on a daily bases.

2022-01-26 09:10 UTC, merged